# Generated by Django 4.0.4 on 2022-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_job_posts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_posts',
            old_name='companywebsite',
            new_name='companymail',
        ),
        migrations.AlterField(
            model_name='job_posts',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=None, max_length=20, null=True),
        ),
    ]
