# Generated by Django 4.0.4 on 2022-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_rename_job_posts_job_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=None, max_length=20, null=True),
        ),
    ]
