# Generated by Django 4.0.4 on 2022-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0010_alter_job_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=None, max_length=20, null=True),
        ),
    ]
