# Generated by Django 4.0.4 on 2022-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0011_alter_job_details_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
