# Generated by Django 4.0.4 on 2022-07-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0012_alter_job_details_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_details',
            new_name='job_profile',
        ),
    ]
