# Generated by Django 4.0.4 on 2022-07-08 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0014_alter_job_profile_id_alter_job_profile_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=None, max_length=20, null=True),
        ),
    ]
