# Generated by Django 4.0.4 on 2022-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0016_alter_job_profile_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_profile',
            name='Requirements',
            field=models.TextField(default='dasdsasdsd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_profile',
            name='benefits',
            field=models.TextField(default='Ddasdsadsadaddffdsdretht'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_profile',
            name='responsibilities',
            field=models.TextField(default='ffertehyhyjjDSF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=None, max_length=20, null=True),
        ),
    ]
