# Generated by Django 4.0.4 on 2022-07-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0020_alter_job_profile_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default=None, max_length=20, null=True),
        ),
    ]
