# Generated by Django 4.0.4 on 2022-07-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0022_alter_job_profile_jobtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_profile',
            old_name='Requirements',
            new_name='requirements',
        ),
    ]
