# Generated by Django 4.0.4 on 2022-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0024_alter_companydetails_companysize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='benefits',
            field=models.TextField(blank=True, default='dsd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='jobdescription',
            field=models.TextField(blank=True, default='dssd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='jobtype',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='requirements',
            field=models.TextField(blank=True, default='DDsdd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='responsibilities',
            field=models.TextField(blank=True, default='dsd'),
            preserve_default=False,
        ),
    ]
