# Generated by Django 4.0.4 on 2022-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0025_alter_job_profile_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_profile',
            name='joblogo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
