# Generated by Django 4.0.4 on 2022-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0027_alter_job_profile_joblogo_alter_job_profile_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(default='', upload_to='companylogos/'),
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='jobtype',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], default=None, max_length=20, null=True),
        ),
    ]
