# Generated by Django 4.0.4 on 2022-06-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_is_admin_alter_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
