# Generated by Django 4.0.4 on 2022-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dateofbirth', models.DateTimeField(null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('Address', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('graduation', models.CharField(max_length=2000)),
                ('college', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('additionalinformation', models.TextField(max_length=1000)),
                ('companyname', models.CharField(max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('DateFrom', models.DateTimeField(null=True)),
                ('DateTo', models.DateTimeField(null=True)),
                ('additionalnformation2', models.TextField(max_length=1000)),
                ('skills', models.CharField(max_length=50)),
                ('skillproficiency', models.IntegerField()),
            ],
        ),
    ]
