# Generated by Django 4.0.4 on 2022-06-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='jobtitle',
            new_name='jobposition',
        ),
    ]
