# Generated by Django 4.0.4 on 2022-06-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_rename_first_name_student_details_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='dateofbirth',
            new_name='dob',
        ),
    ]
