# Generated by Django 4.0.4 on 2022-06-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_rename_dateofbirth_student_details_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='PhoneNumber',
            new_name='pnumber',
        ),
    ]
