# Generated by Django 4.0.4 on 2022-06-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_rename_additionalnformation2_student_details_additionalinformation2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='skillproficiency',
            new_name='skillsproficiency',
        ),
    ]
