# Generated by Django 4.0.4 on 2022-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_rename_skillproficiency_student_details_skillsproficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
