# Generated by Django 4.0.4 on 2022-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_student_details_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
