# Generated by Django 4.0.4 on 2022-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_student_details_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='skillsproficiency',
            field=models.IntegerField(null=True),
        ),
    ]
