# Generated by Django 4.0.4 on 2022-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_alter_student_details_skillsproficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='firstname',
            field=models.CharField(default='some_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='profile_image',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
