# Generated by Django 4.0.4 on 2022-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_alter_student_details_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='pnumber',
            field=models.IntegerField(null=True),
        ),
    ]
