# Generated by Django 4.0.4 on 2022-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_alter_student_details_pnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='pnumber',
            field=models.IntegerField(null=b'I01\n'),
        ),
    ]
