# Generated by Django 4.0.4 on 2022-06-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_alter_student_details_pnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='firstname',
            new_name='name',
        ),
    ]
