# Generated by Django 4.0.4 on 2022-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_rename_firstname_student_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
