# Generated by Django 4.0.4 on 2022-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_alter_student_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='profile_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
