# Generated by Django 4.0.4 on 2022-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_alter_student_details_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='username',
            field=models.CharField(default='sadsdsd', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
