# Generated by Django 4.0.4 on 2022-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_alter_student_details_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
