# Generated by Django 4.0.4 on 2022-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_alter_student_details_pnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='skillsproficiency',
            field=models.IntegerField(null=True),
        ),
    ]
